#Usamos la imagen de nodejs como base
FROM node:20-alpine AS builder

#Se crea y selecciona el directorio para trabajar
WORKDIR /app

#Copiamos archivos de dependencias en el directorio
COPY  package.json yarn.lock ./

#Instalamos dependencias
RUN yarn build


#Para etapa de produccion
FROM nginx:alpine

#Se copia la carpeta compilada y la configuracion de nginx
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etx/nginx/conf.d/default.conf

EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]